[package]
name = "wrapper"
version = "0.1.0"
edition = "2021"


[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
solana-sdk = "*"
bs58 = "*"
bincode = "*"
spl-associated-token-account = "*"

[lib]
crate-type = ["cdylib"]
